# Generated by Django 4.0 on 2022-03-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
        migrations.AlterModelTable(
            name='unitimage',
            table='unit_image',
        ),
    ]
