version: "3.9"

services:
  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/diagon-alley/static
    ports:
      - 80:80
    depends_on:
      - web

  web:
    container_name: web
    build: .
    command: gunicorn ecomm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/diagon-alley
      - static_volume:/diagon-alley/static

volumes:
  static_volume:
