# Generated by Django 4.0 on 2022-02-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='unit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
