# Generated by Django 4.0 on 2022-03-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_update_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/unit_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_images', to='product.unit')),
            ],
            options={
                'verbose_name': 'Unit Image',
                'verbose_name_plural': 'Unit Images',
                'db_table': 'unit_images',
                'ordering': ('unit',),
            },
        ),
    ]
