# Generated by Django 4.0 on 2022-04-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_options_alter_postalcode_options_and_more'),
        ('user', '0002_customuser_phone'),
        ('order', '0002_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='orderuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='orderuseraddress',
            name='address_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user_address', to='address.address', verbose_name='Address'),
        ),
    ]
