# Generated by Django 4.0 on 2022-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='postalcode',
            options={'verbose_name': 'Postal Code', 'verbose_name_plural': 'Postal Codes'},
        ),
        migrations.AddField(
            model_name='postalcode',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='postalcode',
            table='postal_code',
        ),
    ]
