# Generated by Django 4.0 on 2022-03-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_placed_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'order_unit',
                'ordering': ('value',),
            },
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order'),
        ),
        migrations.CreateModel(
            name='OrderUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/unit_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='unit_images', to='order.orderunit')),
            ],
            options={
                'verbose_name': 'Unit Image',
                'verbose_name_plural': 'Unit Images',
                'db_table': 'unit_image',
                'ordering': ('unit',),
            },
        ),
        migrations.AddField(
            model_name='orderunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='units', to='order.orderproduct'),
        ),
    ]
