# Generated by Django 4.0 on 2022-03-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderunit_alter_orderproduct_order_orderunitimage_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderunitimage',
            table='order_unit_images',
        ),
    ]
