# Generated by Django 4.0 on 2022-03-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderunitimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderunitimage',
            table='order_unit_image',
        ),
    ]
