# Generated by Django 4.0 on 2022-03-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderunitimage_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunitimage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_images', to='order.orderunit'),
        ),
    ]
